### ISSUE TITLE
Update aurelia-flux to support aurelia-framework 0.15

### ISSUE THREAD

**Issue by gregoryagu** [tfrydrychewicz/aurelia-flux#11]
When I try to using the Aurelia-flux plugin installed using the JSPM beta, I get the following error message when running the app:

Unhandled promise rejection Error: Pipeline steps can only be added to the root router.

I am guessing the issue is that this is due to the changes made for the JSPM beta in the latest version.

I found this when I was following the steps of Blog post 1.

**Comment by stevies** [comment]
This happened before with aurelia-framework 0.14.0 -it was fixed in 0.14.1. Maybe 0.15.0 has broken things again?  See: https://github.com/tfrydrychewicz/aurelia-flux/issues/9

**Comment by airboss001** [comment]
I am seeing this now after updating everything. Apparently its broke again.
Ok, some more looking and when I change config.js from

```
"github:tfrydrychewicz/aurelia-flux@0.1.6": {
  "aurelia-binding": "github:aurelia/binding@0.8.6",
  "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
  "aurelia-router": "github:aurelia/router@0.10.4", <---------------
  "aurelia-templating": "github:aurelia/templating@0.13.16",
  "bluebird": "npm:bluebird@2.9.34",
  "core-js": "npm:core-js@0.9.18"
},
```

to this

```
"github:tfrydrychewicz/aurelia-flux@0.1.6": {
  "aurelia-binding": "github:aurelia/binding@0.8.6",
  "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
  "aurelia-router": "github:aurelia/router@0.11.0", <---------------
  "aurelia-templating": "github:aurelia/templating@0.13.16",
  "bluebird": "npm:bluebird@2.9.34",
  "core-js": "npm:core-js@0.9.18"
},
```

it doesn't call out the pipeline error anymore.

**Comment by Roustalski** [comment]
Changing the aurelia-router dependency as @airboss001 did also removed the issue for me and it appears to be working so far.

**Comment by charlespockert** [comment]
If in doubt, the best way to check is to look in your `jspm_packages/github/aurelia` folder for any duplicate folder names. 

If you find one, check your `config.js` for the lower of the two versions and remove or update any refs to the new version. 

Most plugins I've used work fine with updates without any work needing to be done to the plugin itself - but obviously if you have mixed framework libraries in a project there's no guarantee that the APIs will match up ok, especially at this early stage with all the breaking changes - so you end up with the old loader passing a load of crap to the new view compiler etc

**Comment by michalru3ch** [comment]
I've also changed aurelia-router dependency as @airboss001 did, the error was resolved but Flux is not working at all! Does anyone experience same issue?

**Comment by rokadias** [comment]
I've updated all my references and I'm still getting the `Unhandled promise rejection Error: Pipeline steps can only be added to the root router` I've forked the repo from #9 and updated the dependencies:
https://github.com/rokadias/aurelia-flux-example

**Comment by airboss001** [comment]
rokadias, you did not update the plugins configuration section to use the 0.11.0 router dependency, its still pointing at 0.10.4

**Comment by plwalters** [comment]
Until v1 this is going to be an issue because the semver changes won't let jspm update work like it should, after v1 this should be no problem.  @tfrydrychewicz can you please update?  We are getting some questions in the official gitter.

**Comment by nojaf** [comment]
Having the same issue created #12
